version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: attendify-frontend
    ports:
      - "${VITE_PORT}:80"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    restart: unless-stopped
